name = "pokemon_battle_api"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/. 

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
wisp = "~> 0.14"
mist = "~> 1.0"
gleam_erlang = "~> 0.25"
gleam_httpc = "~> 2.2"
gleam_http = "~> 3.6"
gleam_json = "~> 1.0"
gleam_otp = "~> 0.10"
birl = "~> 1.6"

[dev-dependencies]
gleeunit = "~> 1.0"
