[package]
name = "csv_sum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "csv_sum"
crate-type = ["cdylib"]

[dependencies]
csv = "1.2.2"
pyo3 = "0.19.0"
rayon = "1.7.0"
