# fly.toml app configuration file generated for 045-deploying-gleam on 2024-08-07T14:35:21+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '045-deploying-gleam'
primary_region = 'lhr'

[build]
  dockerfile = 'erlang.Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
